export const actionType = {
	REGISTER_REQUEST: 'REGISTER_REQUEST',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	//For alert
	SUCCESS: 'ALERT_SUCCESS',
	ERROR: 'ALERT_ERROR',
	CLEAR: 'ALERT_CLEAR',

	//For login/logout
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT: 'LOGOUT',
	SAVE_CREDENTIALS: 'SAVE_CREDENTIALS',

	//For operational data (edit card data with selected value) & kpi data
	OPERATIONAL_STATUS_REQUEST: 'OPERATIONAL_STATUS_REQUEST',
	OPERATIONAL_STATUS_SUCCESS: 'OPERATIONAL_STATUS_SUCCESS',
	OPERATIONAL_STATUS_FAILURE: 'OPERATIONAL_STATUS_FAILURE',
	KPI_DATA_SUCCESS: "KPI_DATA_SUCCESS",

	//For joyride/tour guide
	RUN_TOUR: 'RUN_TOUR',

	//Persona data
	PERSONA_REQUEST: 'PERSONA_REQUEST',
	PERSONA_SUCCESS: 'PERSONA_SUCCESS',
	PERSONA_FAILURE: 'PERSONA_FAILURE',


	//For getting all grid item record
	GRID_ITEM_REQUEST: 'GRID_ITEM_REQUEST',
	GRID_ITEM_SUCCESS: 'GRID_ITEM_SUCCESS',
	GRID_ITEM_FAILURE: 'GRID_ITEM_FAILURE',

	//For show/hide grid items
	SHOW_HIDE_REQUEST: 'SHOW_HIDE_REQUEST',
	TOGGLE_GRID_ITEM_SUCCESS: 'SHOW_GRID_ITEM_SUCCESS',
	TOGGLE_GRID_ITEM_FALIURE: 'SHOW_GRID_ITEM_FALIURE',


	//For getting user data
	USER_REQUEST: 'USER_REQUEST',
	USER_SUCCESS: 'USER_SUCCESS',
	USER_FAILURE: 'USER_FAILURE',

	//For creating user data
	USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
	USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
	USER_CREATE_FAILURE: 'USER_CREATE_FAILURE',

	//For updating user data
	USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
	USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
	USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

	//For deleting user data
	USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
	USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
	USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',

	//For getting user group data
	USER_GROUP_REQUEST: 'USER_GROUP_REQUEST',
	USER_GROUP_SUCCESS: 'USER_GROUP_SUCCESS',
	USER_GROUP_FAILURE: 'USER_GROUP_FAILURE',

	//For creating user group data
	USER_GROUP_CREATE_REQUEST: 'USER_GROUP_CREATE_REQUEST',
	USER_GROUP_CREATE_SUCCESS: 'USER_GROUP_CREATE_SUCCESS',
	USER_GROUP_CREATE_FAILURE: 'USER_GROUP_CREATE_FAILURE',

	//For creating user group data
	USER_GROUP_DELETE_REQUEST: 'USER_GROUP_DELETE_REQUEST',
	USER_GROUP_DELETE_SUCCESS: 'USER_GROUP_DELETE_SUCCESS',
	USER_GROUP_DELETE_FAILURE: 'USER_GROUP_DELETE_FAILURE',

	//For adding user to user group data
	UG_ADD_USER_REQUEST: 'UG_ADD_USER_REQUEST',
	UG_ADD_USER_SUCCESS: 'UG_ADD_USER_SUCCESS',
	UG_ADD_USER_FAILURE: 'UG_ADD_USER_FAILURE',

	//For deleting user to user group data
	UG_DELETE_USER_REQUEST: 'UG_DELETE_USER_REQUEST',
	UG_DELETE_USER_SUCCESS: 'UG_DELETE_USER_SUCCESS',
	UG_DELETE_USER_FAILURE: 'UG_DELETE_USER_FAILURE',

	//For getting job roles data
	JOB_ROLE_REQUEST: 'JOB_ROLE_REQUEST',
	JOB_ROLE_SUCCESS: 'JOB_ROLE_SUCCESS',
	JOB_ROLE_FAILURE: 'JOB_ROLE_FAILURE',

	//For getting table data
	TABLEDATA_REQUEST: 'TABLEDATA_REQUEST',
	TABLEDATA_SUCCESS: 'TABLEDATA_SUCCESS',
	TABLEDATA_FAILURE: 'TABLEDATA_FAILURE',

	//For getting variants data
	VARIANTS_REQUEST: 'VARIANTS_REQUEST',
	VARIANTS_SUCCESS: 'VARIANTS_SUCCESS',
	VARIANTS_FAILURE: 'VARIANTS_FAILURE',

	//For communication module
	TOGGLE_LOCK: 'TOGGLE_LOCK',
	SELECT_DROPDOWN: 'SELECT_DROPDOWN',
	GET_ROW_DETAIL: 'GET_ROW_DETAIL',
	REMOVE_ROW_DETAIL: 'REMOVE_ROW_DETAIL',
	////For adding single communication
	ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
	ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
	ADD_MESSAGE_FAILURE: 'ADD_MESSAGE_FAILURE',
	////For adding last communication in seperate object (lastMessageObj)
	ADD_LAST_MESSAGE_REQUEST: 'ADD_LAST_MESSAGE_REQUEST',
	ADD_LAST_MESSAGE_SUCCESS: 'ADD_LAST_MESSAGE_SUCCESS',
	ADD_LAST_MESSAGE_FAILURE: 'ADD_LAST_MESSAGE_FAILURE',
	////For removing last communication from the seperate object (lastMessageObj)
	REMOVE_LAST_MESSAGE_REQUEST: 'REMOVE_LAST_MESSAGE_REQUEST',
	REMOVE_LAST_MESSAGE_SUCCESS: 'REMOVE_LAST_MESSAGE_SUCCESS',
	REMOVE_LAST_MESSAGE_FAILURE: 'REMOVE_LAST_MESSAGE_FAILURE',
	////For adding search result communication
	SEARCH_MESSAGE_REQUEST: 'SEARCH_MESSAGE_REQUEST',
	SEARCH_MESSAGE_SUCCESS: 'SEARCH_MESSAGE_SUCCESS',
	SEARCH_MESSAGE_FAILURE: 'SEARCH_MESSAGE_FAILURE',
	////For adding initial communication notification
	GET_NOTIFICATION_REQUEST: 'GET_NOTIFICATION_REQUEST',
	GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
	GET_NOTIFICATION_FAILURE: 'GET_NOTIFICATION_FAILURE',
	////For adding instant communication notification
	ADD_NOTIFICATION_REQUEST: 'ADD_NOTIFICATION_REQUEST',
	ADD_NOTIFICATION_SUCCESS: 'ADD_NOTIFICATION_SUCCESS',
	ADD_NOTIFICATION_FAILURE: 'ADD_NOTIFICATION_FAILURE',
	////Add filterDrawer local state to redux global state
	ADD_FILTERS: 'ADD_FILTERS',

	//For creating job role data
	JOB_ROLE_CREATE_REQUEST: 'JOB_ROLE_CREATE_REQUEST',
	JOB_ROLE_CREATE_SUCCESS: 'JOB_ROLE_CREATE_SUCCESS',
	JOB_ROLE_CREATE_FAILURE: 'JOB_ROLE_CREATE_FAILURE',

	//For updating job role data
	JOB_ROLE_UPDATE_REQUEST: 'JOB_ROLE_UPDATE_REQUEST',
	JOB_ROLE_UPDATE_SUCCESS: 'JOB_ROLE_UPDATE_SUCCESS',
	JOB_ROLE_UPDATE_FAILURE: 'JOB_ROLE_UPDATE_FAILURE',

	//For deleting job role data
	JOB_ROLE_DELETE_REQUEST: 'JOB_ROLE_DELETE_REQUEST',
	JOB_ROLE_DELETE_SUCCESS: 'JOB_ROLE_DELETE_SUCCESS',
	JOB_ROLE_DELETE_FAILURE: 'JOB_ROLE_DELETE_FAILURE',

	//For getting system roles data
	SYSTEM_ROLE_REQUEST: 'SYSTEM_ROLE_REQUEST',
	SYSTEM_ROLE_SUCCESS: 'SYSTEM_ROLE_SUCCESS',
	SYSTEM_ROLE_FAILURE: 'SYSTEM_ROLE_FAILURE',

	//For creating system role data
	SYSTEM_ROLE_CREATE_REQUEST: 'SYSTEM_ROLE_CREATE_REQUEST',
	SYSTEM_ROLE_CREATE_SUCCESS: 'SYSTEM_ROLE_CREATE_SUCCESS',
	SYSTEM_ROLE_CREATE_FAILURE: 'SYSTEM_ROLE_CREATE_FAILURE',

	//For updating system role data
	SYSTEM_ROLE_UPDATE_REQUEST: 'SYSTEM_ROLE_UPDATE_REQUEST',
	SYSTEM_ROLE_UPDATE_SUCCESS: 'SYSTEM_ROLE_UPDATE_SUCCESS',
	SYSTEM_ROLE_UPDATE_FAILURE: 'SYSTEM_ROLE_UPDATE_FAILURE',

	//For deleting system role data
	SYSTEM_ROLE_DELETE_REQUEST: 'SYSTEM_ROLE_DELETE_REQUEST',
	SYSTEM_ROLE_DELETE_SUCCESS: 'SYSTEM_ROLE_DELETE_SUCCESS',
	SYSTEM_ROLE_DELETE_FAILURE: 'SYSTEM_ROLE_DELETE_FAILURE',
	//For getting logged in user's settings
	USER_SETTINGS_REQUEST: 'USER_SETTINGS_REQUEST',
	USER_SETTINGS_SUCCESS: 'USER_SETTINGS_SUCCESS',
	USER_SETTINGS_FAILURE: 'USER_SETTINGS_FAILURE',

	//For requesting user's settings update & success/failure
	USER_SETTINGS_UPDATE_DASHBOARD: 'USER_SETTINGS_UPDATE_DASHBOARD',
	USER_SETTINGS_UPDATE_REPORTS: 'USER_SETTINGS_UPDATE_REPORTS',
	USER_SETTINGS_UPDATE_ACCOUNT: 'USER_SETTINGS_UPDATE_ACCOUNT',

	USER_SETTINGS_UPDATE_SUCCESS: 'USER_SETTINGS_UPDATE_SUCCESS',
	USER_SETTINGS_UPDATE_FAILURE: 'USER_SETTINGS_UPDATE_FAILURE',

	//Add Master Filter dropdown value
	ADD_DROPDOWN_VALUE_REQUEST: 'ADD_DROPDOWN_VALUE_REQUEST',
	ADD_DROPDOWN_VALUE_SUCCESS: 'ADD_DROPDOWN_VALUE_SUCCESS',
	ADD_DROPDOWN_VALUE_FAILURE: 'ADD_DROPDOWN_VALUE_FAILURE',

};