export const constants = {
    OPEN_PO: 'openpoID',
    BACKLOG: 'backlogID',
    SKU: 'skuID',
    INVENTORY: 'inventoryID',
    ORDER: 'orderKey',
    PERSID_BACKLOG: 'backlog',
    PERSID_BACKLOGDETAILED: 'backlogDetailed',
    PERSID_CONSOL: 'consol',
    PERSID_OPENPO: 'openPo',
    PERSID_POVSBACKLOG: 'poVsBacklog',
    PERSID_FREIGHTORDERSEA: 'freightOrderSeaSnapshot',
    PERSID_SHORTAGE: 'shortage',
    PERSID_OPENORDER: 'openOrder',
    PERSID_SHIPMENTS: 'shipments',
    PERSID_DEALTRACKER: 'dealTracker',
    PERSID_BUILDPLAN: 'buildPlan',
    PERSID_BOOKINGVSFORECAST: 'bookingVsForecast',
    ACTUAL_PLANS: 'actualsPlans',
    OPENPO_DETAILED: 'openPoDetailed ',
    PD_INVENTORY: 'inventory',
    SUPPLIERS: 'suppliers',
    REBALANCE_QUANTITY: 'rebalanceQuantity',
    TAG_LIST: ['#general', '#cancelbacklog', '#escalate', '#excess', '#forecast', '#rebalance', '#requestForInformation', '#ringfence', '#shortage-raisePO', '#shortage-repackageBTS', '#shortage-reconfigureLM'],
};